/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomDropdown {
        "debounceTime": number;
    }
    interface CustomOption {
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCustomDropdownElement extends Components.CustomDropdown, HTMLStencilElement {
    }
    var HTMLCustomDropdownElement: {
        prototype: HTMLCustomDropdownElement;
        new (): HTMLCustomDropdownElement;
    };
    interface HTMLCustomOptionElement extends Components.CustomOption, HTMLStencilElement {
    }
    var HTMLCustomOptionElement: {
        prototype: HTMLCustomOptionElement;
        new (): HTMLCustomOptionElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "custom-dropdown": HTMLCustomDropdownElement;
        "custom-option": HTMLCustomOptionElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CustomDropdown {
        "debounceTime"?: number;
    }
    interface CustomOption {
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "custom-dropdown": CustomDropdown;
        "custom-option": CustomOption;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-dropdown": LocalJSX.CustomDropdown & JSXBase.HTMLAttributes<HTMLCustomDropdownElement>;
            "custom-option": LocalJSX.CustomOption & JSXBase.HTMLAttributes<HTMLCustomOptionElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
